Repository kartik4949/AutoDeploy, pull requests merged in 2021-08, with the labels that each got.

#3 :sparkles: Added simple loadtest for stuctured data
  autodeploy/testing/load_test.py
  autodeploy/utils/utils.py
Labels: enhancement

#1 git ignore has .DS_Store and added requirements
  .gitignore
  requirements.txt
Labels: documentation

#8 Prometheus basic model metric expose
  assests/developer.md
  autodeploy/base/base_infere.py
  autodeploy/base/base_moniter_driver.py
  autodeploy/config/logging.conf
  autodeploy/database/models.py
  autodeploy/handlers/handlers.py
  autodeploy/loader/loaders.py
  autodeploy/loader/model_loader.py
  autodeploy/logger/logger.py
  autodeploy/monitor.py
  autodeploy/monitor/__init__.py
  autodeploy/monitor/drift_detection.py
  autodeploy/monitor/monitor.py
  autodeploy/monitor/prometheus.py
  autodeploy/routers/model.py
  autodeploy/routers/predict.py
  autodeploy/schema/schema.py
  autodeploy/service/builder.py
  autodeploy/testing/load_test.py
  autodeploy/utils/utils.py
  configs/config.yaml
Labels: enhancement, monitoring
